# Generated by Django 6.0.7 on 2026-07-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Published', 'published'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
    ]
